output_root: '../'
#pytorch_data_dir: '/home/pgrad1/2417023z/DFU2024/STEGO/src/data/DFUdata/imgs/val/'
pytorch_data_dir: '/home/pgrad1/2417023z/DFU2024/dino_norm/DFU_test/'
experiment_name: "DFUdata"
res: 224
batch_size: 20
num_workers: 8
run_crf: True


model_paths:
  - "/home/pgrad1/2417023z/DFU2024/STEGO/checkpoint/DFUdata/directory_exp1_date_Aug19_22-12-57/epoch=11-step=1459.ckpt"
  


hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
